export const ITEM_ICONS: Record<string, string> = {
  Desc_Stone_C: "Stone_256.png",
  Desc_OreIron_C: "IconDesc_iron_new_256.png",
  Desc_OreCopper_C: "IconDesc_copper_new_256.png",
  Desc_OreGold_C: "IconDesc_CateriumOre_256.png",
  Desc_Coal_C: "IconDesc_CoalOre_256.png",
  Desc_RawQuartz_C: "IconDesc_QuartzResource_256.png",
  Desc_Sulfur_C: "Sulfur_256.png",
  Desc_OreBauxite_C: "IconDesc_Bauxite_256.png",
  Desc_SAM_C: "IconDesc_SameOre_256.png",
  Desc_OreUranium_C: "IconDesc_UraniumOre_256.png",
  Desc_Water_C: "LiquidWater_Pipe_256.png",
  Desc_LiquidOil_C: "LiquidOil_Pipe_256.png",
  Desc_NitrogenGas_C: "IconDesc_PackagedNitrogen_256.png",
  Desc_IronIngot_C: "IconDesc_IronIngot_256.png",
  Desc_CopperIngot_C: "IconDesc_CopperIngot_256.png",
  Desc_GoldIngot_C: "IconDesc_CateriumIngot_256.png",
  Desc_SteelIngot_C: "IconDesc_SteelIngot_256.png",
  Desc_AluminumIngot_C: "IconDesc_AluminiumIngot_256.png",
  Desc_FicsiteIngot_C: "IconDesc_FicsiteIngot_256.png",
  Desc_Cement_C: "IconDesc_Concrete_256.png",
  Desc_QuartzCrystal_C: "IconDesc_QuartzCrystal_256.png",
  Desc_Silica_C: "IconDesc_Silica_256.png",
  Desc_CopperDust_C: "IconDesc_CopperDust_256.png",
  Desc_PolymerResin_C: "IconDesc_PolymerResin_256.png",
  Desc_PetroleumCoke_C: "IconDesc_PetroleumCoke_256.png",
  Desc_AluminumScrap_C: "IconDesc_AluminiumScrap_256.png",
  Desc_AlienProtein_C: "IconDesc_AlienProtein_256.png",
  Desc_AlienDNACapsule_C: "IconDesc_AlienDNA_256.png",
  Desc_HeavyOilResidue_C: "IconDesc_LiquidHeavyOilResidue_Pipe_256.png",
  Desc_LiquidFuel_C: "IconDesc_LiquidFuel_Pipe_256.png",
  Desc_LiquidBiofuel_C: "IconDesc_LiquidBiofuel_Pipe_256.png",
  Desc_LiquidTurboFuel_C: "IconDesc_LiquidTurboFuel_Pipe_256.png",
  Desc_AluminaSolution_C: "LiquidAlumina_Pipe_256.png",
  Desc_SulfuricAcid_C: "IconDesc_LiquidSulfuricAcid_Pipe_256.png",
  Desc_NitricAcid_C: "IconDesc_NitricAcid_256.png",
  Desc_DissolvedSilica_C: "IconDesc_DissolvedSilica_256.png",
  Desc_RocketFuel_C: "IconDesc_RocketFuelPipe_256.png",
  Desc_IonizedFuel_C: "IconDesc_IonizedFuel_256.png",
  Desc_DarkEnergy_C: "IconDesc_DarkEnergy_256.png",
  Desc_QuantumEnergy_C: "IconDesc_QuantumEnergy_256.png",
  Desc_IronRod_C: "IconDesc_IronRods_256.png",
  Desc_IronScrew_C: "IconDesc_IronScrews_256.png",
  Desc_IronPlate_C: "IconDesc_IronPlates_256.png",
  Desc_IronPlateReinforced_C: "IconDesc_ReinforcedIronPlates_256.png",
  Desc_CopperSheet_C: "IconDesc_CopperSheet_256.png",
  Desc_AluminumPlate_C: "IconDesc_AluminiumSheet_256.png",
  Desc_AluminumCasing_C: "IconDesc_AluminiumCasing_256.png",
  Desc_SteelPipe_C: "IconDesc_SteelPipe_256.png",
  Desc_SteelPlate_C: "IconDesc_SteelBeam_256.png",
  Desc_SteelPlateReinforced_C: "IconDesc_EncasedSteelBeam_256.png",
  Desc_ModularFrame_C: "IconDesc_ModularFrame_256.png",
  Desc_ModularFrameHeavy_C: "IconDesc_ModularFrameHeavy_256.png",
  Desc_ModularFrameFused_C: "IconDesc_FusedModularFrame_256.png",
  Desc_FicsiteMesh_C: "IconDesc_FicsiteMesh_256.png",
  Desc_Plastic_C: "IconDesc_Plastic_256.png",
  Desc_Rubber_C: "IconDesc_Rubber_256.png",
  Desc_Rotor_C: "IconDesc_Rotor_256.png",
  Desc_Stator_C: "IconDesc_Stator_256.png",
  Desc_Battery_C: "IconDesc_Battery_256.png",
  Desc_Motor_C: "IconDesc_Engine_256.png",
  Desc_AluminumPlateReinforced_C: "IconDesc_Heatsink_256.png",
  Desc_CoolingSystem_C: "IconDesc_CoolingSystem_256.png",
  Desc_MotorLightweight_C: "IconDesc_TurboMotor_256.png",
  Desc_Wire_C: "IconDesc_Wire_256.png",
  Desc_Cable_C: "IconDesc_Cables_256.png",
  Desc_HighSpeedWire_C: "IconDesc_Quickwire_256.png",
  Desc_CircuitBoard_C: "IconDesc_CircuitBoard_256.png",
  Desc_CircuitBoardHighSpeed_C: "IconDesc_AILimiter_256.png",
  Desc_HighSpeedConnector_C: "IconDesc_HighSpeedConnector_256.png",
  Desc_SAMIngot_C: "IconDesc_ReanimatedSam_256.png",
  Desc_SAMFluctuator_C: "IconDesc_SamFluctuator_256.png",
  Desc_Computer_C: "IconDesc_Computer_256.png",
  Desc_ComputerSuper_C: "IconDesc_QuantumComputer_256.png",
  Desc_ModularFrameLightweight_C: "IconDesc_RadioControlUnit_256.png",
  Desc_CrystalOscillator_C: "IconDesc_CrystalOscillator_256.png",
  Desc_QuantumOscillator_C: "IconDesc_SuperPositionOscillator_256.png",
  Desc_Diamond_C: "IconDesc_Diamonds_256.png",
  Desc_DarkMatter_C: "IconDesc_ExoticMatter_256.png",
  Desc_TimeCrystal_C: "IconDesc_TimeCrystal_256.png",
  Desc_SingularityCell_C: "IconDesc_SingularityCell_256.png",
  Desc_TemporalProcessor_C: "IconDesc_TemporalProcessor_256.png",
  Desc_EmptyCanister_C: "IconDesc_EmptyCannister_256.png",
  Desc_FluidCanister_C: "IconDesc_EmptyCannister_256.png",
  Desc_GasTank_C: "IconDesc_PressureTank_256.png",
  Desc_PressureConversionCube_C: "IconDesc_ConversionCube_256.png",
  Desc_PackagedWater_C: "IconDesc_PackagedWater_256.png",
  Desc_PackagedAlumina_C: "IconDesc_PackagedAluminaSolution_256.png",
  Desc_PackagedSulfuricAcid_C: "IconDesc_PckagedSulphuricAcid_256.png",
  Desc_PackagedNitricAcid_C: "IconDesc_PackagedNitricAcid_256.png",
  Desc_PackagedNitrogenGas_C: "IconDesc_PackagedNitrogen_256.png",
  Desc_CompactedCoal_C: "IconDesc_CompactedCoal_256.png",
  Desc_Fuel_C: "IconDesc_Fuel_256.png",
  Desc_TurboFuel_C: "IconDesc_TurboFuel_256.png",
  Desc_PackagedRocketFuel_C: "IconDesc_PackagedRocketFuel_256.png",
  Desc_PackagedIonizedFuel_C: "IconDesc_IonizedRocketFuel_256.png",
  Desc_Gunpowder_C: "IconDesc_Gunpowder_256.png",
  Desc_GunpowderMK2_C: "IconDesc_GunpowderMk2_256.png",
  Desc_Filter_C: "IconDesc_GasMaskFilter_256.png",
  Desc_HazmatFilter_C: "IconDesc_HazmatFilter_256.png",
  Desc_ElectromagneticControlRod_C: "IconDesc_ElectromagneticControlRod_256.png",
  Desc_UraniumCell_C: "IconDesc_NuclearCell_256.png",
  Desc_NonFissibleUranium_C: "IconDesc_NonFissileUranium_256.png",
  Desc_PlutoniumPellet_C: "IconDesc_PlutoniumPellet_256.png",
  Desc_PlutoniumCell_C: "IconDesc_EncasedPlutoniumCell_256.png",
  Desc_Ficsonium_C: "IconDesc_FicsoniumCell_256.png",
  Desc_NuclearWaste_C: "IconDesc_NuclearWaste_256.png",
  Desc_PlutoniumWaste_C: "IconDesc_PlutoniumWaste_256.png",
  Desc_Crystal_C: "PowerSlugGreen_256.png",
  Desc_Crystal_mk2_C: "PowerSlugYellow_256.png",
  Desc_Crystal_mk3_C: "PowerSlugPurple_256.png",
  Desc_SpaceElevatorPart_1_C: "IconDesc_SpelevatorPart_1_256.png",
  Desc_SpaceElevatorPart_2_C: "IconDesc_SpelevatorPart_2_256.png",
  Desc_SpaceElevatorPart_3_C: "SpelevatorPart_3_256.png",
  Desc_SpaceElevatorPart_4_C: "IconDesc_SpelevatorPart_4_256.png",
  Desc_SpaceElevatorPart_5_C: "IconDesc_SpelevatorPart_5_256.png",
  Desc_SpaceElevatorPart_6_C: "IconDesc_MagneticFieldGenerator_256.png",
  Desc_SpaceElevatorPart_7_C: "IconDesc_AssemblyDirectorSystem_256.png",
  Desc_SpaceElevatorPart_8_C: "IconDesc_ThermalPropulsionRocket_256.png",
  Desc_SpaceElevatorPart_9_C: "IconDesc_NuclearPasta_256.png",
  Desc_SpaceElevatorPart_10_C: "IconDesc_BiochemicalSculptor_256.png",
  Desc_SpaceElevatorPart_11_C: "IconDesc_BallisticWarpDrive_256.png",
  Desc_SpaceElevatorPart_12_C: "IconDesc_AIExpension_256.png",
};

export const FACTORY_ICONS: Record<string, string> = {
  Desc_SmelterMk1_C: "IconDesc_SmelterMk1_256.png",
  Desc_ConstructorMk1_C: "IconDesc_ConstructorMk1_256.png",
  Desc_AssemblerMk1_C: "IconDesc_AssemblerMk1_256.png",
  Desc_FoundryMk1_C: "IconDesc_Foundry_256.png",
  Desc_ManufacturerMk1_C: "IconDesc_Manufacturer_256.png",
  Desc_OilRefinery_C: "IconDesc_OilRefinery_256.png",
  Desc_Blender_C: "IconDesc_Blender_256.png",
  Desc_Packager_C: "IconDesc_Packager_256.png",
};

export function getItemIconUrl(itemId?: string) {
  if (!itemId) return undefined;
  const filename = ITEM_ICONS[itemId];
  return filename ? `/icons/items/${filename}` : undefined;
}

export function getFactoryIconUrl(factoryId?: string) {
  if (!factoryId) return undefined;
  const filename = FACTORY_ICONS[factoryId];
  return filename ? `/icons/factories/${filename}` : undefined;
}
